2024-06-01 16:05:12,881 Loaded preprocessed data from /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/fetches/preprocessed_data.csv
2024-06-01 16:05:12,882 Error training model: 'Target'
2024-06-01 16:08:17,977 Loaded preprocessed data from /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/fetches/preprocessed_data.csv
2024-06-01 16:08:18,762 Model trained with accuracy: 0.5314685314685315
2024-06-01 16:08:18,874 Model saved to /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/ensemble_model.pkl
2024-06-01 16:14:34,078 Loaded preprocessed data from /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/fetches/preprocessed_data.csv
2024-06-01 16:14:34,722 Model trained with accuracy: 0.4755244755244755
2024-06-01 16:14:34,810 Model saved to /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/ensemble_model.pkl
2024-06-01 17:05:05,770 Loaded preprocessed data from /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/fetches/preprocessed_data.csv
2024-06-01 17:05:06,651 Model trained with accuracy: 0.5
2024-06-01 17:05:06,652 Precision: 0.4930555555555556, Recall: 0.5035460992907801, F1 Score: 0.4982456140350877
2024-06-01 17:05:06,738 Model saved to /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/ensemble_model.pkl
2024-06-01 17:06:59,805 Loaded preprocessed data from /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/fetches/preprocessed_data.csv
2024-06-01 17:07:43,139 Model trained with accuracy: 0.5034965034965035
2024-06-01 17:07:43,140 Precision: 0.496551724137931, Recall: 0.5106382978723404, F1 Score: 0.5034965034965035
2024-06-01 17:07:43,196 Model saved to /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/ensemble_model.pkl
2024-06-01 17:10:14,737 Loaded preprocessed data from /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/fetches/preprocessed_data.csv
2024-06-01 17:10:18,114 Error training model: 
All the 108 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
36 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/ensemble/_forest.py", line 363, in fit
    X, y = self._validate_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1273, in check_X_y
    X = check_array(
        ^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1007, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 746, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 2153, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '2024-05-31 22:08:00'

--------------------------------------------------------------------------------
72 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/ensemble/_forest.py", line 363, in fit
    X, y = self._validate_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1273, in check_X_y
    X = check_array(
        ^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1007, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 746, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 2153, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '2024-05-31 19:29:00'

2024-06-01 17:11:02,155 Loaded preprocessed data from /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/fetches/preprocessed_data.csv
2024-06-01 17:11:05,750 Error training model: 
All the 108 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
36 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/ensemble/_forest.py", line 363, in fit
    X, y = self._validate_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1273, in check_X_y
    X = check_array(
        ^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1007, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 746, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 2153, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '2024-05-31 22:08:00'

--------------------------------------------------------------------------------
72 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/ensemble/_forest.py", line 363, in fit
    X, y = self._validate_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1273, in check_X_y
    X = check_array(
        ^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1007, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 746, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 2153, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '2024-05-31 19:29:00'

2024-06-01 17:30:43,409 Loaded preprocessed data from /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/fetches/preprocessed_data.csv
2024-06-01 17:32:33,550 Loaded preprocessed data from /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/fetches/preprocessed_data.csv
2024-06-01 17:33:16,318 Model trained with accuracy: 0.5
2024-06-01 17:33:16,319 Precision: 0.5035971223021583, Recall: 0.48951048951048953, F1 Score: 0.49645390070921985
2024-06-01 17:33:16,417 Model saved to /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/ensemble_model.pkl
2024-06-01 17:37:53,193 Loaded preprocessed data from /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/fetches/preprocessed_data.csv
2024-06-01 17:41:06,353 Model trained with accuracy: 0.5229681978798587
2024-06-01 17:41:06,353 Precision: 0.5100671140939598, Recall: 0.5507246376811594, F1 Score: 0.5296167247386759
2024-06-01 17:41:06,596 Model saved to /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/ensemble_model.pkl
2024-06-01 17:46:55,798 Loaded preprocessed data from /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/fetches/preprocessed_data.csv
2024-06-01 18:00:34,768 Loaded preprocessed data from /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/fetches/preprocessed_data.csv
2024-06-01 18:14:34,510 Loaded preprocessed data from /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/fetches/preprocessed_data.csv
2024-06-01 18:14:51,636 Loaded preprocessed data from /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/fetches/preprocessed_data.csv
2024-06-01 18:17:01,445 Loaded preprocessed data from /Users/gorkemberkeyuksel/Documents/GitHub/Lunapki/crypto_trading_bot/Bot_Logs/fetches/preprocessed_data.csv
